<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pedidos.Domain\Vendas.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\ClientesCommands\AdicionarEnderecoDoCliente\" />
    <Folder Include="Commands\ClientesCommands\AlterarEnderecoDoCliente\" />
    <Folder Include="Commands\ClientesCommands\DefinirEnderecoPrincipalDoCliente\" />
    <Folder Include="Commands\ClientesCommands\AtualizarPerfilDoCliente\" />
    <Folder Include="Commands\ClientesCommands\BloquearCliente\" />
    <Folder Include="Commands\ClientesCommands\AtivarCliente\" />
    <Folder Include="Commands\ClientesCommands\CriarCliente\" />
  </ItemGroup>

</Project>
